models:
  - name: gpt-3.5-turbo
    backend: llama
    parameters:
      model: models/ggml-gpt4all-j.bin
      context_size: 2048
      temperature: 0.7
      top_p: 0.9
      stream: true

  - name: stable-diffusion
    backend: stablediffusion
    parameters:
      model: models/stable-diffusion.ckpt
      stream: true 